// app/app/(auth)/(tabs)/sets.tsx
import { useEffect } from 'react'

import Loader from '@/components/Loader'
import ScreenSection from '@/components/ScreenSection'
import ScreenTitle from '@/components/ScreenTitle'
import { ScreenView } from '@/components/ScreenView'
import ScrollList from '@/components/ScrollList'

import useAPI from '@/hooks/useAPI'

import { ISetList } from '@/types/ISetList'
import SetCard from '@/components/Set/Card'

export default function SetsScreen() {
  const {
    fetchData: fetchSets,
    data: setsData,
    isLoading: isLoadingSets,
  } = useAPI<ISetList>()

  useEffect(() => {
    fetchSets('sets')
  }, [])

  const setList = () => {
    return setsData ? setsData.results : []
  }

  return (
    <ScreenView>
      <ScreenSection>
        <ScreenTitle>Sets 📚</ScreenTitle>
      </ScreenSection>
      <ScreenSection>
        <ScrollList>
          {isLoadingSets && <Loader />}
          {!isLoadingSets &&
            setList().map((set) => <SetCard key={set.id} set={set} />)}
        </ScrollList>
      </ScreenSection>
    </ScreenView>
  )
}

// studyapp/pages/sets/index.vue
<script setup lang="ts">
const {
  data,
  execute: fetchSetList,
  isLoading,
} = useAPI<IResponse<ISet>>('/sets/')

onMounted(() => {
  fetchSetList()
})

const setList = computed<ISet[]>(() => data?.value?.results || [])
</script>
<template>
  <div>
    <h1>Sets page!</h1>
    <div v-if="isLoading">Loading data...</div>
    <set-card v-for="set in setList" :key="set.id" :set="set" />
  </div>
</template>

<style scoped></style>
