// frontend/components/Set/Detail.vue
<script setup lang="ts">
const props = defineProps<{
  set: ISet
}>()

const router = useRouter()
const startGame = (mode: string) => {
  router.push(`/game/${props.set?.id}`)
}

const emptyTermsLength = computed(() => props.set.terms.length === 0)
</script>
<template>
  <div>
    <div class="flex flex-col text-center items-center mb-3">
      <s-title>{{ set?.name }}</s-title>
      <p class="my-2">{{ set?.description }}</p>
      <set-image
        v-if="set.picture"
        class="mb-3"
        :url="set.picture"
        :width="300"
        :height="300"
        :alt="`Picture of set ${set.name}`"
      />
      <s-button :is-disabled="emptyTermsLength" @click="startGame">
        ▶️ Practice
      </s-button>
    </div>
    <div>
      <p v-if="emptyTermsLength">No terms in this set.</p>
      <div class="flex justify-center flex-wrap">
        <term-card v-for="term in set.terms" :key="term.id" :term="term" />
      </div>
    </div>
  </div>
</template>

<style scoped></style>

// app/components/Set/Detail.tsx
import Loader from '@/components/Loader'
import ScreenSection from '@/components/ScreenSection'
import ScreenTitle from '@/components/ScreenTitle'
import ScrollList from '@/components/ScrollList'
import TermCard from '@/components/Term/Card'
import SetPicture from '@/components/Set/Picture'
import { useRouter } from 'expo-router'

import { Text, StyleSheet, FlatList, View } from 'react-native'
import { ISet } from '@/types/ISet'
import SButton from '@/components/SButton'
import { EGameType } from '@/types/EGameType'
import SetGameButtons from './SetGameButtons'

interface SetDetailProps {
  set?: ISet | null
  isLoading?: boolean
}

export default function SetDetail({ set, isLoading }: SetDetailProps) {
  const router = useRouter()
  const startGame = (mode: string) => {
    router.push(`/play/${set?.id}?mode=${mode}`)
  }

  const emptyTermsLength = () => set?.terms.length === 0
  return (
    <ScrollList>
      <ScreenSection>
        <SetPicture
          alt={`Picture of ${set?.name}`}
          height={100}
          url={set?.picture}
        />
        <ScreenTitle>{set?.name}</ScreenTitle>
        {set?.description && <Text>{set?.description}</Text>}
        <SetGameButtons
          areButtonsDisabled={emptyTermsLength()}
          isLoading={isLoading}
          startGame={startGame}
        />
      </ScreenSection>
      <ScreenSection title="Terms">
        {isLoading && <Loader />}
        <FlatList
          data={set?.terms}
          renderItem={({ item: term }) => (
            <TermCard key={term.id} term={term} />
          )}
          numColumns={2}
        />
        {emptyTermsLength() && <Text>No terms in this set.</Text>}
      </ScreenSection>
    </ScrollList>
  )
}
